# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  config.vm.forward_port 15671, 15671
  config.vm.forward_port 15672, 15672
  config.vm.forward_port 5671, 5671
  config.vm.forward_port 5601, 5601
  config.vm.forward_port 5672, 5672
  config.vm.forward_port 9300, 9300
  config.vm.forward_port 9200, 9200
  config.vm.forward_port 80, 2080
  config.vm.forward_port 443, 2443
  

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui
  config.vm.provision :shell do |sh|
    sh.path = 'start.sh'
  end
  config.vm.provision :puppet, :module_path => ["../../", "../../../modules"] do |puppet|
     puppet.manifests_path = "."
     puppet.manifest_file  = "init.pp"
  end
  
end
