#!/bin/bash
# This cleans up docker images that are no longer used
# This always complains about an image that is used by a container so we redirect
# the output so we don't get mailed about it every day.
FORCE_IMAGE_REMOVAL=1 /usr/sbin/docker-gc
