Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network "forwarded_port", guest: 8280, host: 8280
  config.vm.network "forwarded_port", host: 8080, guest: 80
    config.vm.network "forwarded_port", host: 8443, guest: 443
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]  
  end
  
  config.vm.provision :shell do |sh|
    sh.path = 'start.sh'

  end
  config.vm.provision :puppet, :module_path => ["../../", "../../../modules"] do |puppet|
     puppet.manifests_path = "."
     puppet.manifest_file  = "init.pp"
  end
end
