#!/bin/sh
# Backup all the databases

test -d /var/backups/mysql || exit 1

# Uses the debian maintainance user
mysqldump --defaults-extra-file=/etc/mysql/debian.cnf --all-databases --single-transaction > /var/backups/mysql/mysql.backup